name: upskill-sprint1-ci
services:
  jenkins:
    build: ./jenkins
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
  sonarqube:
    image: sonarqube:community@sha256:f85ffdce5b54a6cf595ff570486c0a5b26e2c744d6fda6a790275d6f966450f3
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    restart: unless-stopped

volumes:
  jenkins_home:
  sonar_data:
  sonar_extensions:
  sonar_logs:
